create extension if not exists pgcrypto;
create table if not exists public.categories(id uuid primary key default gen_random_uuid(),name text unique not null,created_at timestamptz default now());
create table if not exists public.products(id uuid primary key default gen_random_uuid(),name text not null,slug text unique not null,description text default '',category text not null,price numeric(12,2) not null check(price>=0),stock integer not null default 0 check(stock>=0),sizes jsonb not null default '[]',colors jsonb not null default '[]',image_url text,image_path text,active boolean not null default true,created_at timestamptz default now(),updated_at timestamptz default now());
create table if not exists public.orders(id bigint generated by default as identity primary key,order_number text unique not null,customer_name text not null,customer_email text not null,customer_phone text,shipping_address text,shipping_city text,shipping_postal_code text,total numeric(12,2) not null,items jsonb not null default '[]',status text not null default 'PENDING',payment_status text not null default 'PENDING',shipping_status text not null default 'PENDING',tracking_code text,carrier text,mp_preference_id text,mp_payment_id text,mp_status text,mp_status_detail text,created_at timestamptz default now(),updated_at timestamptz default now());
insert into public.categories(name) values('Mujer'),('Hombre'),('Accesorios') on conflict(name) do nothing;
insert into public.products(name,slug,description,category,price,stock,sizes,colors) values('Remera Essential','remera-essential','Remera de algodón de corte clásico.','Mujer',25000,20,'["S","M","L","XL"]','["Negro","Blanco"]'),('Campera Urban','campera-urban','Campera liviana de estilo urbano.','Hombre',65000,12,'["M","L","XL"]','["Negro","Verde"]') on conflict(slug) do nothing;
create or replace function public.decrement_product_stock(p_product_id uuid,p_quantity integer) returns void language plpgsql security definer as $$ begin update public.products set stock=stock-p_quantity,updated_at=now() where id=p_product_id and stock>=p_quantity; if not found then raise exception 'Stock insuficiente'; end if; end; $$;
alter table public.products enable row level security;alter table public.categories enable row level security;alter table public.orders enable row level security;
drop policy if exists "public read active products" on public.products;create policy "public read active products" on public.products for select using(active=true or auth.role()='authenticated');
drop policy if exists "public read categories" on public.categories;create policy "public read categories" on public.categories for select using(true);
drop policy if exists "admin manage products" on public.products;create policy "admin manage products" on public.products for all to authenticated using(true) with check(true);
drop policy if exists "admin read orders" on public.orders;create policy "admin read orders" on public.orders for select to authenticated using(true);
drop policy if exists "admin update orders" on public.orders;create policy "admin update orders" on public.orders for update to authenticated using(true) with check(true);
create or replace function public.get_order_tracking(p_order_number text,p_email text) returns table(order_number text,status text,payment_status text,shipping_status text,total numeric,created_at timestamptz,tracking_code text,carrier text) language sql security definer set search_path=public as $$ select o.order_number,o.status,o.payment_status,o.shipping_status,o.total,o.created_at,o.tracking_code,o.carrier from public.orders o where o.order_number=p_order_number and lower(o.customer_email)=lower(p_email) limit 1 $$;
grant execute on function public.get_order_tracking(text,text) to anon,authenticated;
-- Storage: crear el bucket desde Dashboard con nombre product-images y marcarlo público.
-- Policies para el bucket. Si las creás desde SQL, ejecutá estas sentencias luego de crear el bucket:
drop policy if exists "public read product images" on storage.objects;
create policy "public read product images" on storage.objects for select to public using(bucket_id='product-images');
drop policy if exists "authenticated upload product images" on storage.objects;
create policy "authenticated upload product images" on storage.objects for insert to authenticated with check(bucket_id='product-images');
drop policy if exists "authenticated update product images" on storage.objects;
create policy "authenticated update product images" on storage.objects for update to authenticated using(bucket_id='product-images') with check(bucket_id='product-images');
drop policy if exists "authenticated delete product images" on storage.objects;
create policy "authenticated delete product images" on storage.objects for delete to authenticated using(bucket_id='product-images');
